version: 2
jobs:
  build:
    docker:
      - image: jumperio/vlab-gcc-arm:latest
    steps:
      - checkout
      - run:
          name: build
          command: |
            sed -i -E 's/[A-Z]:\\.*\\workspace_[^\\]+\\[^\\]+\\/..\//' Debug/makefile
            make -C Debug all
      - store_artifacts:
          path: build/
